server:
  port: 8081
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
      bindings:
        message-out:
          destination: test
          contentType: application/json

